#!/usr/bin/env node
/**
 * tokens/build.js
 * Generates:
 *   tokens/_tokens.scss  — SCSS variables + :root CSS custom properties
 *   tokens/tokens.ts     — TypeScript typed constants
 *
 * Usage: node tokens/build.js
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const TOKENS_JSON = path.join(__dirname, 'tokens.json');
const OUT_SCSS    = path.join(__dirname, '_tokens.scss');
const OUT_TS      = path.join(__dirname, 'tokens.ts');

const tokens = JSON.parse(fs.readFileSync(TOKENS_JSON, 'utf8'));

// ─── SCSS output ────────────────────────────────────────────────────────────

const scssLines = [
    '// AUTO-GENERATED by tokens/build.js — do not edit manually',
    '// Source: tokens/tokens.json',
    '//',
    '// This file exposes Odoo design tokens as CSS custom properties.',
    '// Import this file AFTER primary_variables.scss in each asset bundle.',
    '',
    ':root {',
];

function flattenTokens(obj, prefix = '') {
    for (const [key, val] of Object.entries(obj)) {
        if (val && typeof val === 'object' && 'value' in val) {
            // Leaf token
            if (val.css) {
                scssLines.push(`  ${val.css}: ${val.value};`);
            }
        } else if (val && typeof val === 'object') {
            flattenTokens(val, prefix ? `${prefix}-${key}` : key);
        }
    }
}

flattenTokens(tokens);
scssLines.push('}');
scssLines.push('');

fs.writeFileSync(OUT_SCSS, scssLines.join('\n'), 'utf8');
console.log(`✓ ${path.relative(process.cwd(), OUT_SCSS)}`);

// ─── TypeScript output ───────────────────────────────────────────────────────

const tsLines = [
    '// AUTO-GENERATED by tokens/build.js — do not edit manually',
    '// Source: tokens/tokens.json',
    '',
    '/** Odoo design tokens for use in React Native (NativeWind / inline styles) */',
    '',
];

function buildTsObject(obj, depth = 0) {
    const indent = '  '.repeat(depth);
    const lines  = [];
    for (const [key, val] of Object.entries(obj)) {
        const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `'${key}'`;
        if (val && typeof val === 'object' && 'value' in val) {
            lines.push(`${indent}  ${safeKey}: ${JSON.stringify(val.value)},`);
        } else if (val && typeof val === 'object') {
            lines.push(`${indent}  ${safeKey}: {`);
            lines.push(...buildTsObject(val, depth + 1));
            lines.push(`${indent}  },`);
        }
    }
    return lines;
}

tsLines.push('export const tokens = {');
tsLines.push(...buildTsObject(tokens));
tsLines.push('} as const;');
tsLines.push('');
tsLines.push('export type Tokens = typeof tokens;');
tsLines.push('');

// Convenience flat exports for NativeWind tailwind.config.js
const colors = tokens.color;
tsLines.push('/** Flat color palette for NativeWind tailwind.config.js */');
tsLines.push('export const palette = {');
tsLines.push("  brand: {");
for (const [k, v] of Object.entries(colors.brand || {})) {
    if (v && 'value' in v) tsLines.push(`    ${k}: ${JSON.stringify(v.value)},`);
}
tsLines.push("  },");
tsLines.push("  status: {");
for (const [k, v] of Object.entries(colors.status || {})) {
    if (v && 'value' in v) tsLines.push(`    ${k}: ${JSON.stringify(v.value)},`);
}
tsLines.push("  },");
tsLines.push("  gray: {");
for (const [k, v] of Object.entries(colors.gray || {})) {
    if (v && 'value' in v) tsLines.push(`    '${k}': ${JSON.stringify(v.value)},`);
}
tsLines.push("  },");
tsLines.push('} as const;');
tsLines.push('');

fs.writeFileSync(OUT_TS, tsLines.join('\n'), 'utf8');
console.log(`✓ ${path.relative(process.cwd(), OUT_TS)}`);

console.log('\n✅ Token build complete.');
