// AUTO-GENERATED by tokens/build.js — do not edit manually
// Source: tokens/tokens.json

/** Odoo design tokens for use in React Native (NativeWind / inline styles) */

export const tokens = {
  color: {
    brand: {
      community: "#71639e",
      enterprise: "#714B67",
      action: "#017e84",
      primary: "#71639e",
      secondary: "#8f8f8f",
      odoo: "#71639e",
    },
    status: {
      success: "#28a745",
      warning: "#ffac00",
      danger: "#dc3545",
      info: "#17a2b8",
    },
    gray: {
      '100': "#f8f9fa",
      '200': "#e9ecef",
      '300': "#dee2e6",
      '400': "#ced4da",
      '500': "#adb5bd",
      '600': "#6c757d",
      '700': "#495057",
      '800': "#343a40",
      '900': "#212529",
    },
    ui: {
      'view-bg': "#ffffff",
      'webclient-bg': "#f8f9fa",
      'main-text': "#212529",
      'main-link': "#614593",
      favorite: "#f3cc00",
      'component-active-bg': "#e2ddef",
      'component-active-border': "#71639e",
    },
  },
  spacing: {
    spacer: "16px",
    'form-unit': "5px",
    'horizontal-padding': "16px",
    'dropdown-hpadding': "20px",
  },
  radius: {
    sm: "3px",
    md: "4px",
    lg: "6px",
    xl: "8px",
    full: "9999px",
  },
  shadow: {
    sm: "0 1px 2px rgba(0,0,0,0.06)",
    md: "0 2px 8px rgba(0,0,0,0.10)",
    lg: "0 4px 20px rgba(0,0,0,0.14)",
  },
  typography: {
    'size-base': "14px",
    'size-base-touch': "16px",
    'size-sm': "13px",
    'size-xs': "12px",
    'weight-normal': "400",
    'weight-medium': "500",
    'weight-bold': "700",
    'line-height-base': "1.5",
  },
  navbar: {
    height: "46px",
    'height-slim': "40px",
  },
  zindex: {
    navbar: "1000",
    sidebar: "1010",
    dropdown: "1020",
    modal: "1050",
    popover: "1070",
    tooltip: "1080",
  },
  transition: {
    fast: "100ms",
    base: "150ms",
    slow: "200ms",
    'easing-enter': "cubic-bezier(0.05, 0.7, 0.1, 1.0)",
    'easing-exit': "cubic-bezier(0.3, 0.0, 0.8, 0.15)",
  },
} as const;

export type Tokens = typeof tokens;

/** Flat color palette for NativeWind tailwind.config.js */
export const palette = {
  brand: {
    community: "#71639e",
    enterprise: "#714B67",
    action: "#017e84",
    primary: "#71639e",
    secondary: "#8f8f8f",
    odoo: "#71639e",
  },
  status: {
    success: "#28a745",
    warning: "#ffac00",
    danger: "#dc3545",
    info: "#17a2b8",
  },
  gray: {
    '100': "#f8f9fa",
    '200': "#e9ecef",
    '300': "#dee2e6",
    '400': "#ced4da",
    '500': "#adb5bd",
    '600': "#6c757d",
    '700': "#495057",
    '800': "#343a40",
    '900': "#212529",
  },
} as const;
